name: WakaTime on Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          commit_message: 'Pixsuvy : auto fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: tanmaysingh3856
          commit_user_email: tanmaysingh3856@gmail.com
          commit_author: tanmaysingh3856 <tanmaysingh3856@gmail.com>
